remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

include: ["assets/css/style.css"]

title: "Niels Dutrievoz"
description: "PhD Student in polar climate modelling"

header_image: "images/banner.jpeg"

include:
  - _includes/mathjax.html



